env:
  es2021: true

parserOptions:
  ecmaVersion: 2022
  sourceType: module

globals:
  ARGV: readonly
  Debugger: readonly
  GIRepositoryGType: readonly
  globalThis: readonly
  imports: readonly
  Intl: readonly
  log: readonly
  logError: readonly
  print: readonly
  printerr: readonly
  console: readonly
  TextEncoder: readonly
  TextDecoder: readonly

rules:
  # Possible Errors
  no-await-in-loop: error
  no-extra-parens:
    - error
    - all
    - conditionalAssign: false
      nestedBinaryExpressions: false
      returnAssign: false
  no-template-curly-in-string: error
  no-unreachable-loop: error

  # Best Practices
  array-callback-return: error
  consistent-return: error
  curly:
    - error
    - multi-or-nest
    - consistent
  default-case-last: error
  dot-location:
    - error
    - property
  dot-notation: error
  eqeqeq: error
  no-caller: error
  no-constructor-return: error
  no-else-return: error
  no-extend-native: error
  no-extra-bind: error
  no-floating-decimal: error
  no-implicit-coercion:
    - error
    - allow:
        - '!!'
  no-implied-eval: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-multi-spaces: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal-escape: error
  no-proto: error
  no-return-assign: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-return: error
  no-void: error
  prefer-promise-reject-errors: error
  prefer-regex-literals: error
  wrap-iife:
    - error
    - inside

  # Variables
  no-shadow: error
  no-unused-vars:
    - error
    - varsIgnorePattern: ^_
      argsIgnorePattern: ^_

  # Stylistic Issues
  array-bracket-newline:
    - error
    - consistent
  array-bracket-spacing: error
  block-spacing: error
  brace-style: error
  comma-dangle:
    - error
    - always-multiline
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  eol-last: error
  func-call-spacing: error
  indent:
    - error
    - 4
    - ignoredNodes:
        - CallExpression > ObjectExpression
      MemberExpression: off
      SwitchCase: 1
  key-spacing: error
  keyword-spacing: error
  linebreak-style: error
  lines-between-class-members: error
  new-parens: error
  no-array-constructor: error
  no-lonely-if: error
  no-multiple-empty-lines:
    - error
    - max: 2
  no-new-object: error
  no-tabs: error
  no-trailing-spaces: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-curly-newline:
    - error
    - consistent: true
      multiline: true
  object-curly-spacing: error
  operator-assignment: error
  operator-linebreak:
    - error
    - after
    - overrides:
        '?': ignore
        ':': ignore
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  semi-spacing: error
  semi-style: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  switch-colon-spacing: error
  template-curly-spacing: error
  unicode-bom: error

  # ECMAScript 6
  arrow-body-style: error
  arrow-parens:
    - error
    - as-needed
  arrow-spacing: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  rest-spread-spacing: error
  symbol-description: error
  template-tag-spacing: error
